name: e_learning_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^9.1.1
  # Code Generator (main used with cubit & retrofit)
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  # JSON Serialization
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  # Dependency Injection
  get_it: ^8.0.3
  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  retrofit_generator: ^9.2.0
  pretty_dio_logger: ^1.4.0
  # Local Database
  shared_preferences: ^2.5.3
  # Localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  # for splash screen
  flutter_native_splash: ^2.4.4
  # for responsive design
  flutter_screenutil: ^5.9.3
  # for UI components
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/svgs/onboarding/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true
